### ISSUE TITLE
PermissionError when trying with the example data

### ISSUE THREAD

**Issue by Ludoalevesque** [rubykong/cbig_network_correspondence#9]
I followed the instructions on the github page to install NCT and I tried to run the following commands :

import cbig_network_correspondence as cnc

atlas_names_list = ["EG17","MG360J12"]
example = cnc.load_example
# the example config file
print(example.example_config)
# the path to the example data
print(example.example_nii)
ref_params = cnc.compute_overlap_with_atlases.DataParams(example.example_config, example.example_nii)
cnc.compute_overlap_with_atlases.network_correspondence(ref_params, atlas_names_list,"/home/rkong/storage/Temporary/NCTexample/example_results")

I got the following error :

Single dimension data is provided. Visualize network correspondence as circular chart.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ludo/miniconda3/envs/NCT_env/lib/python3.9/site-packages/cbig_network_correspondence/compute_overlap_with_atlases.py", line 698, in network_correspondence
    vis_report.report_data_network_correspondence(df,out_dir)
  File "/home/ludo/miniconda3/envs/NCT_env/lib/python3.9/site-packages/cbig_network_correspondence/visualize_report_lib.py", line 633, in report_data_network_correspondence
    os.makedirs(out_dir)
  File "/home/ludo/miniconda3/envs/NCT_env/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ludo/miniconda3/envs/NCT_env/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "/home/ludo/miniconda3/envs/NCT_env/lib/python3.9/os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  [Previous line repeated 1 more time]
  File "/home/ludo/miniconda3/envs/NCT_env/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/rkong'

**Comment by rubykong** [comment]
@Ludoalevesque You need to change your output path to your own directory (see highlighted part below).
ref_params = cnc.compute_overlap_with_atlases.DataParams(example.example_config, example.example_nii)
cnc.compute_overlap_with_atlases.network_correspondence(ref_params, atlas_names_list,**_"/home/rkong/storage/Temporary/NCTexample/example_results"_**)
